import io
import tempfile
import unittest
from zipfile import ZipFile

from tools import validate_dfiq_archive


class ValidateDFIQArchiveTest(unittest.TestCase):
    def test_committed_archive_is_consistent(self):
        # tests/dfiq_test_data/dfiq_test_data.zip is regenerated by hand
        # whenever its yaml fixtures change (e.g. GHSA-6xf2-8436-rgvf); this
        # guards against its uuids/parent_ids silently drifting out of sync,
        # which would otherwise make DFIQ import skip linking the
        # scenario/facet/question hierarchy (update_parents(soft_fail=True)).
        errors = validate_dfiq_archive.validate(
            "tests/dfiq_test_data/dfiq_test_data.zip"
        )
        self.assertEqual(errors, [])

    def test_rejects_non_yaml_files(self):
        buffer = io.BytesIO()
        with ZipFile(buffer, "w") as archive:
            archive.writestr(
                "S1003.yaml",
                "type: scenario\nid: S1003\nuuid: "
                "00000000-0000-4000-8000-000000000001\n",
            )
            archive.writestr("setup.sh", "#!/bin/sh\necho pwned\n")

        with tempfile.NamedTemporaryFile(suffix=".zip") as archive_file:
            archive_file.write(buffer.getvalue())
            archive_file.flush()
            errors = validate_dfiq_archive.validate(archive_file.name)

        self.assertIn("setup.sh is not a .yaml file", errors)

    def test_rejects_disguised_executable(self):
        buffer = io.BytesIO()
        with ZipFile(buffer, "w") as archive:
            archive.writestr(
                "S1003.yaml",
                "type: scenario\nid: S1003\nuuid: "
                "00000000-0000-4000-8000-000000000001\n",
            )
            # A shell script renamed to *.yaml to slip past an extension-only check.
            archive.writestr("payload.yaml", "#!/bin/sh\nrm -rf /\n")

        with tempfile.NamedTemporaryFile(suffix=".zip") as archive_file:
            archive_file.write(buffer.getvalue())
            archive_file.flush()
            errors = validate_dfiq_archive.validate(archive_file.name)

        self.assertTrue(
            any("payload.yaml" in error and "detected as" in error for error in errors)
        )
