import unittest

from tools import validate_dfiq_archive


class ValidateDFIQArchiveTest(unittest.TestCase):
    def test_committed_archive_is_consistent(self):
        # tests/dfiq_test_data/dfiq_test_data.zip is regenerated by hand
        # whenever its yaml fixtures change (e.g. GHSA-6xf2-8436-rgvf); this
        # guards against its uuids/parent_ids silently drifting out of sync,
        # which would otherwise make DFIQ import skip linking the
        # scenario/facet/question hierarchy (update_parents(soft_fail=True)).
        errors = validate_dfiq_archive.validate(
            "tests/dfiq_test_data/dfiq_test_data.zip"
        )
        self.assertEqual(errors, [])
