name: DFIQ archive consistency

on: [pull_request]

permissions:
  contents: read

jobs:

  dfiq-consistency:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - run:
        sudo apt-get update && sudo apt-get install -y python3-pip && sudo pip3 install uv
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: uv sync --group dev
    - name: Install magika
      run: uv pip install magika
    - name: Validate DFIQ archive consistency
      run: uv run python -m unittest tests.tools.validate_dfiq_archive -v
