name: Build Docker images

on: [pull_request]

jobs:
  push_to_registries:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./extras/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
